### ISSUE TITLE
minimum viable product for release

### ISSUE THREAD

**Issue by slwu89** [dd-harp/MicroMoB#28]
to-do:

- [x] address #25 somewhere, perhaps in a vignette, although a test to check that multi-patch simulation works right would be nice. (done #29)
- [x] non-trivial model of aquatic dynamics, perhaps the [beverton-holt](https://github.com/dd-harp/RAMP-Model-Library/blob/main/MicroMoB/Micro-Mosquito-Aquatic-BH.Rmd) one or another in RAMP (done #33)
- [x] a queueing model of human infection, like [this paper](https://malariajournal.biomedcentral.com/articles/10.1186/1475-2875-8-87) (done #34)
- [x] vignette on blood feeding, like https://dd-harp.github.io/MicroWNV/articles/Bloodmeal.html
- [x] vignette describing software design, using diagrams to show how components interact. (#36 #37 #38, same for above item)

**Comment by slwu89** [comment]
completed.
